INSERT INTO m_sex (m_sex_id, m_sex_logic_name, m_sex_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (1, 'man', '男', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false) ON CONFLICT DO NOTHING;
INSERT INTO m_sex (m_sex_id, m_sex_logic_name, m_sex_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (2, 'weman', '女', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;

INSERT INTO m_director (m_director_id, m_director_logic_name, m_director_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (1, 'Representative Director and President', '代表取締役社長', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_director (m_director_id, m_director_logic_name, m_director_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (2, 'Senior Managing Director', '専務取締役', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_director (m_director_id, m_director_logic_name, m_director_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (3, 'Managing Director', '常務取締役', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_director (m_director_id, m_director_logic_name, m_director_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (4, 'General Manager', '本部長', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_director (m_director_id, m_director_logic_name, m_director_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (5, 'Manager', '部長', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_director (m_director_id, m_director_logic_name, m_director_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (6, 'Deputy manager', '次長', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_director (m_director_id, m_director_logic_name, m_director_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (7, 'Manager', '課長', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_director (m_director_id, m_director_logic_name, m_director_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (8, 'Chief', '主任', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_director (m_director_id, m_director_logic_name, m_director_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (9, 'General', '一般', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;

INSERT INTO m_department (m_department_id, m_department_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (1, '経営管理部', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_department (m_department_id, m_department_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (2, '人事部', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_department (m_department_id, m_department_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (3, 'セキュリティ管理部', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_department (m_department_id, m_department_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (4, 'リスク管理部', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_department (m_department_id, m_department_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (5, 'システム開発部', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_department (m_department_id, m_department_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (6, 'システム技術部', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
INSERT INTO m_department (m_department_id, m_department_physics_name, created_at, create_user, create_program, updated_at, update_user, update_program, is_deleted) VALUES (7, '営業部', NOW(), 'Developer', 'Query', NOW(), 'Developer', 'Query', false)  ON CONFLICT DO NOTHING;
